### ISSUE TITLE
TypeError: rawDirectiveValue is not iterable

### ISSUE THREAD

**Issue by simevidas** [helmetjs/helmet#242]
I just upgraded to version 4.0.0, and now my server logs this error:

```
/var/app/current/node_modules/helmet/dist/middlewares/content-security-policy/index.js:55
            for (const element of rawDirectiveValue) {
                                  ^

TypeError: rawDirectiveValue is not iterable
    at /var/app/current/node_modules/helmet/dist/middlewares/content-security-policy/index.js:55:35
    at Array.map (<anonymous>)
    at getHeaderValueFromOptions (/var/app/current/node_modules/helmet/dist/middlewares/content-security-policy/index.js:40:10)
    at Object.contentSecurityPolicy [as default] (/var/app/current/node_modules/helmet/dist/middlewares/content-security-policy/index.js:75:25)
    at helmet (/var/app/current/node_modules/helmet/dist/index.js:31:67)
    at Object.<anonymous> (/var/app/current/server.js:58:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webplatformnews-site@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webplatformnews-site@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

My setup is as follows:

```js
app.use(
  helmet({
    referrerPolicy: {
      policy: 'no-referrer-when-downgrade',
    },
    contentSecurityPolicy: {
      directives: {
        defaultSrc: [`'none'`],
        connectSrc: [`'self'`, 'https://weekly.webplatform.news'],
        imgSrc: [`'self'`, 'data:', 'https://avatars.githubusercontent.com'],
        mediaSrc: [`'self'`],
        objectSrc: [`'self'`],
        scriptSrc: [
          `'self'`,
          `'sha256-n7ZzvuyDda0y+emzKfApX2LivZHa1IWeX2+uVqHjVo4='`,
          `'sha256-QeMnt6qA/Vqb0MIbiIL/35VdVuv0Jb6c/1uHgamXwnw='`,
        ],
        workerSrc: [`'self'`],
        styleSrc: [`'self'`],
        manifestSrc: [`'self'`],
        baseUri: [`'none'`],
        formAction: [`'self'`, 'https://weekly.webplatform.news'],
        frameAncestors: [`'self'`],
        upgradeInsecureRequests: true,
        reportUri: 'https://webplatformnews.report-uri.com/r/d/csp/enforce',
      },
    },
    featurePolicy: {
      features: {
        geolocation: [`'none'`],
        midi: [`'none'`],
        payment: [`'none'`],
        camera: [`'none'`],
        usb: [`'none'`],
        magnetometer: [`'none'`],
        accelerometer: [`'none'`],
        speaker: [`'none'`],
        ambientLightSensor: [`'none'`],
        gyroscope: [`'none'`],
        syncXhr: [`'none'`],
        microphone: [`'none'`],
      },
    },
  })
);
```

I’m investigating what’s going on here.

**Comment by EvanHahn** [comment]
This is likely because `upgradeInsecureRequests` is `true`. To set a directive with no values, try `upgradeInsecureRequests: []`.

Also, as another note, `featurePolicy` was deprecated (because the header has been deprecated). If you still need this behavior, try [the `feature-policy` package](https://github.com/helmetjs/feature-policy).

I'm going to close this issue because I believe that's the answer, but let me know if that's wrong and I'll reopen.

**Comment by simevidas** [comment]
Thank you for the quick response. I am no longer getting the error after changing the line to `upgradeInsecureRequests: []` and removing the `featurePolicy` field in its entirety.

**Comment by EvanHahn** [comment]
Great! If there's anything else I can help with, feel free to open a new issue.
